name: Publish Package to npmjs
on:
  push:
    branches:
      - master
  # release:
  #   types: [created]
  # pull_request:
  #   branches: 
  #     - main
  #   types: [closed] 
jobs:
  # if_merged:
  #   if: github.event.pull_request.merged == true
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lataest code
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install packages
        run: npm ci
      - name: Runs ESLint 
        id: build-package
        run: npm run lint
      # - name: Publish package to npm registry 
      #   if: steps.build-package.outcome == 'success' 
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}